//! Example module: polls `blockchain_module.get_cryptarchia_info` every 5 s
//! through the generated client. `provider_gen.rs` is generated by
//! `nix run .#generate`.

include!("provider_gen.rs");

use logos_blockchain_client::BlockchainModuleClient;
use std::sync::atomic::{AtomicI64, Ordering};
use std::sync::OnceLock;
use std::time::Duration;

const TAG: &str = "blockchain_client_example";
const POLL_INTERVAL: Duration = Duration::from_secs(5);

static LAST_HEIGHT: AtomicI64 = AtomicI64::new(-1);
static POLL_COUNT: AtomicI64 = AtomicI64::new(0);
// The generated scaffold already imports std::sync::Mutex; refer to it by path.
static LAST_INFO: std::sync::Mutex<String> = std::sync::Mutex::new(String::new());
static LAST_ERROR: std::sync::Mutex<String> = std::sync::Mutex::new(String::new());

fn blockchain() -> &'static BlockchainModuleClient {
    static CLIENT: OnceLock<BlockchainModuleClient> = OnceLock::new();
    CLIENT.get_or_init(BlockchainModuleClient::new)
}

/// Polls once; `value` in the module's `{success, value, error}` envelope is a JSON string.
fn poll_once() -> i64 {
    POLL_COUNT.fetch_add(1, Ordering::SeqCst);
    match blockchain().get_cryptarchia_info() {
        Ok(reply) => {
            let ok = reply.get("success").and_then(|s| s.as_bool()).unwrap_or(true);
            if !ok {
                let err = reply
                    .get("error")
                    .map(|e| e.to_string())
                    .unwrap_or_else(|| reply.to_string());
                eprintln!("{TAG}: get_cryptarchia_info refused: {err}");
                *LAST_ERROR.lock().unwrap() = err;
                return -1;
            }
            let info = match reply.get("value") {
                Some(serde_json::Value::String(s)) => {
                    serde_json::from_str(s).unwrap_or(serde_json::Value::String(s.clone()))
                }
                Some(v) => v.clone(),
                None => reply.clone(),
            };
            let height = info.get("height").and_then(|h| h.as_i64()).unwrap_or(-1);
            let slot = info.get("slot").and_then(|s| s.as_i64()).unwrap_or(-1);
            let mode = info
                .get("mode")
                .map(|m| m.to_string())
                .unwrap_or_else(|| "?".to_string());
            eprintln!("{TAG}: height={height} slot={slot} mode={mode}");
            LAST_HEIGHT.store(height, Ordering::SeqCst);
            *LAST_INFO.lock().unwrap() = info.to_string();
            LAST_ERROR.lock().unwrap().clear();
            height
        }
        Err(e) => {
            eprintln!("{TAG}: get_cryptarchia_info failed: {e}");
            *LAST_ERROR.lock().unwrap() = e.to_string();
            -1
        }
    }
}

#[derive(Default)]
struct Example;

impl BlockchainClientExampleModule for Example {
    fn last_height(&mut self) -> i64 {
        LAST_HEIGHT.load(Ordering::SeqCst)
    }

    fn poll_count(&mut self) -> i64 {
        POLL_COUNT.load(Ordering::SeqCst)
    }

    fn last_info(&mut self) -> String {
        LAST_INFO.lock().unwrap().clone()
    }

    fn last_error(&mut self) -> String {
        LAST_ERROR.lock().unwrap().clone()
    }

    fn poll_now(&mut self) -> i64 {
        poll_once()
    }

    fn on_context_ready(&mut self, ctx: &RustModuleContext) {
        eprintln!(
            "{TAG}: ready (instance_id={}, persistence={}); polling every {}s",
            ctx.instance_id,
            ctx.instance_persistence_path,
            POLL_INTERVAL.as_secs()
        );
        std::thread::spawn(|| loop {
            poll_once();
            std::thread::sleep(POLL_INTERVAL);
        });
    }
}

#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<Example>();
}
